spring.application.name=labtrack

# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/labtrack_db
spring.datasource.username=postgres
spring.datasource.password=JE25@patta

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG

jwt.secret=ZmY4ZjYwZmQ0OTM3YjQ3M2JjYjE2MzQxYTY5YjQwNTM5MWY5M2Y4YjNkOTFiNTYwMTEwZDIwYTI3MjJjY2Q3Yw==
jwt.expiration=86400000



logging.level.org.springframework.security=TRACE
logging.level.com.prangyajeet.labtrack=DEBUG

