ALTER TABLE inventory_items

ADD COLUMN IF NOT EXISTS manufacturer_name VARCHAR(150),

ADD COLUMN IF NOT EXISTS brand_name VARCHAR(100),

ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(100),

ADD COLUMN IF NOT EXISTS purchase_order_number VARCHAR(100),

ADD COLUMN IF NOT EXISTS batch_number VARCHAR(100),

ADD COLUMN IF NOT EXISTS serial_number VARCHAR(100),

ADD COLUMN IF NOT EXISTS manufacturing_date DATE,

ADD COLUMN IF NOT EXISTS receiving_date DATE,

ADD COLUMN IF NOT EXISTS warranty_expiry DATE,

ADD COLUMN IF NOT EXISTS shelf_number VARCHAR(50),

ADD COLUMN IF NOT EXISTS cabinet_number VARCHAR(50),

ADD COLUMN IF NOT EXISTS reorder_quantity INTEGER,

ADD COLUMN IF NOT EXISTS hazard_level VARCHAR(50),

ADD COLUMN IF NOT EXISTS storage_condition VARCHAR(150);