package com.prangyajeet.labtrack.report.entity;

public enum ReportType {

    FULL_REPORT,

    INVENTORY_STOCK,
    LOW_STOCK,
    OUT_OF_STOCK,
    STOCK_IN,
    STOCK_OUT,
    DAILY_CONSUMABLES,
    EXPIRY,

    SUPPLIER_PURCHASES,
    SUPPLIER_ITEMS,

    EQUIPMENT_REGISTER,
    WARRANTY,
    AMC,
    AMC_EXPIRY,
    MAINTENANCE_HISTORY,
    MAINTENANCE_COST,

    BREAKAGE_REGISTER,
    DEPARTMENT_BREAKAGE,
    PERSON_BREAKAGE,
    PENDING_RECOVERY,
    PAID_RECOVERY,
    WAIVED_RECOVERY,
    BREAKAGE_COST
}
